##############################################################
# Kubernetes spec for running the 'climbing comp' application
# https://github.com/jcookin/climbing-comp
##############################################################
---
apiVersion: v1
kind: Namespace
metadata:
  name: climbing-comp
  labels:
    name: climbing-comp
    app: climbing-comp

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: climbing-comp-pv
  app: climbing-comp
spec:
  capacity:
    storage: 10GiB
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-filesystem-ec-1
---
apiVersion: v1
kind: Service
metadata:
  name: climbing-comp-app-svc
spec:
  selector:
    app: climbing-comp
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: climbing-comp-dashboard-svc
spec:
  selector:
    app: climbing-comp-dashboard
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: climbing-comp-nig
  labels:
    name: climbing-comp
spec:
  tls:
    TODO:
  rules:
  - host: comp.reclusivy.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: climbing-comp-app-svc
            port: 
              number: 80
      - pathType: Prefix
        path: "/dashboard"
        backend:
          service:
            name: climbing-comp-dashboard-svc
            port: 
              number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: climbing-comp-app
spec:
  selector:
    matchLabels:
      app: climbing-comp-app
  template:
    metadata:
      labels:
        app: climbing-comp-app
    spec:
      containers:
      - name: climbing-comp-app
        image: climbing-comp:latest
        environment:
          - DB_PATH: /data
          - DB_NAME: climbing.db
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
        ports:
        - containerPort: 8080
        volumeMounts:
          - TODO:
    volumes:
      - TODO:
---

