{
 "title": "Competition Stats",
 "description": "Stats for the competition",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Leaderboard (points)",
   "type": "table",
   "description": "Competitor leaderboard by points",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "-- CLIMBERS ROUTE_NAME IS_SENT\n-- SELECT routes.route_name, attempts_sends.is_sent, climbers.username\n-- FROM routes\n-- LEFT JOIN attempts_sends ON attempts_sends.route_id=routes.route_id\n-- LEFT JOIN climbers ON climbers.climber_id=attempts_sends.climber_id\n-- ORDER BY is_sent DESC;\n\nSELECT climbers.username as Username, SUM(routes.route_points) as Points\nFROM routes\nLEFT JOIN attempts_sends ON attempts_sends.route_id=routes.route_id\nLEFT JOIN climbers ON climbers.climber_id=attempts_sends.climber_id WHERE attempts_sends.is_sent=1\nGROUP BY climbers.climber_id\nORDER BY Points DESC;",
     "rawQueryText": "-- CLIMBERS ROUTE_NAME IS_SENT\n-- SELECT routes.route_name, attempts_sends.is_sent, climbers.username\n-- FROM routes\n-- LEFT JOIN attempts_sends ON attempts_sends.route_id=routes.route_id\n-- LEFT JOIN climbers ON climbers.climber_id=attempts_sends.climber_id\n-- ORDER BY is_sent DESC;\n\nSELECT climbers.username as Username, SUM(routes.route_points) as Points\nFROM routes\nLEFT JOIN attempts_sends ON attempts_sends.route_id=routes.route_id\nLEFT JOIN climbers ON climbers.climber_id=attempts_sends.climber_id WHERE attempts_sends.is_sent=1\nGROUP BY climbers.climber_id\nORDER BY Points DESC;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Num Intermediate Routes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT COUNT(route_grade) FROM routes WHERE route_grade<='4';",
     "rawQueryText": "SELECT COUNT(route_grade) FROM routes WHERE route_grade<='4';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Num Advanced Routes",
   "type": "stat",
   "description": "Number of Advanced Routes",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT COUNT(route_grade) FROM routes WHERE route_grade>='5';",
     "rawQueryText": "SELECT COUNT(route_grade) FROM routes WHERE route_grade>='5';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}