{
 "title": "Usage Stats",
 "description": "Stats for app usage",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Registered Users",
   "type": "stat",
   "description": "Shows all the users using the app",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT count(climber_id) FROM climbers;\n",
     "rawQueryText": "SELECT count(climber_id) FROM climbers;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Number of Routes",
   "type": "stat",
   "description": "The total number of routes entered into the system",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT count(route_id) FROM routes;",
     "rawQueryText": "SELECT count(route_id) FROM routes;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Number of Teams",
   "type": "stat",
   "description": "Total number of teams in the comp",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT count(team_id) FROM teams;",
     "rawQueryText": "SELECT count(team_id) FROM teams;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}